const SEVERITY_EMOJI = {
  CRITICAL: "🔴",
  HIGH: "🟠",
  MEDIUM: "🟡",
  LOW: "🔵",
};

const CATEGORY_EMOJI = {
  BUG: "🐛",
  SECURITY: "🔐",
  PERFORMANCE: "⚡",
  QUALITY: "🧹",
};

const CATEGORY_LABEL = {
  BUG: "Bugs",
  SECURITY: "Security",
  PERFORMANCE: "Performance",
  QUALITY: "Quality",
};

const SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW"];
const CATEGORY_ORDER = ["BUG", "SECURITY", "PERFORMANCE", "QUALITY"];

/**
 * Formats a single finding into the body of an inline GitHub review comment.
 * Matching Requirement 7 format.
 *
 * @param {object} finding
 * @returns {string}
 */
function formatInlineComment(finding) {
  const sevEmoji = SEVERITY_EMOJI[finding.severity] || "⚠️";
  const catEmoji = CATEGORY_EMOJI[finding.category] || "🔍";

  const lines = [
    `### ${sevEmoji} ${finding.severity} — ${catEmoji} ${finding.category}`,
    `**${finding.title}**`,
    ``,
    finding.explanation,
    ``,
    `**Why this matters / Impact:**`,
    finding.impact,
    ``,
    `**Suggested fix:**`,
    finding.suggested_fix,
  ];

  if (finding.suggested_code && finding.suggested_code.trim()) {
    lines.push(
      ``,
      "```suggestion",
      finding.suggested_code.trim(),
      "```"
    );
  }

  return lines.join("\n");
}

/**
 * Formats the top-of-PR summary comment.
 * Matching Requirement 8 format.
 *
 * @param {object} params
 * @param {Array<object>} params.findings Current active findings
 * @param {Array<object>} params.newFindings Findings being posted in this run
 * @param {number} params.skippedDuplicateCount Number of duplicates skipped
 * @param {number} params.totalFilesReviewed Number of changed files reviewed
 * @param {string} params.summary Overall AI summary string
 * @param {string} params.model Model name used
 * @returns {string}
 */
function formatSummary({
  findings = [],
  newFindings = [],
  skippedDuplicateCount = 0,
  totalFilesReviewed = 0,
  summary = "",
  model = "gemini-2.5-flash",
}) {
  const severityCounts = { CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0 };
  const categoryCounts = { BUG: 0, SECURITY: 0, PERFORMANCE: 0, QUALITY: 0 };

  // Count against all findings detected in this PR state
  for (const f of findings) {
    if (severityCounts[f.severity] !== undefined) {
      severityCounts[f.severity]++;
    }
    if (categoryCounts[f.category] !== undefined) {
      categoryCounts[f.category]++;
    }
  }

  const lines = [
    `## 🤖 PR GUARDIAN — AI CODE REVIEW`,
    ``,
    `**Files reviewed:** ${totalFilesReviewed}`,
    ``,
    `### Findings:`,
    `🔴 **Critical:** ${severityCounts.CRITICAL}`,
    `🟠 **High:** ${severityCounts.HIGH}`,
    `🟡 **Medium:** ${severityCounts.MEDIUM}`,
    `🔵 **Low:** ${severityCounts.LOW}`,
    ``,
    `### Categories:`,
    `🐛 **Bugs:** ${categoryCounts.BUG}`,
    `🔐 **Security:** ${categoryCounts.SECURITY}`,
    `⚡ **Performance:** ${categoryCounts.PERFORMANCE}`,
    `🧹 **Quality:** ${categoryCounts.QUALITY}`,
    ``,
    `### Summary:`,
    summary || (findings.length === 0 ? "All checks passed! No issues detected in this pull request." : "Review completed."),
  ];

  if (skippedDuplicateCount > 0) {
    lines.push(
      ``,
      `> ℹ️ **Re-review Note:** Skipped **${skippedDuplicateCount}** finding(s) already reported in prior commits.`
    );
  }

  if (findings.length > 0) {
    lines.push(
      ``,
      `<details>`,
      `<summary>📋 <b>Detailed Findings Breakdown (${findings.length})</b></summary>`,
      ``,
      `| Severity | Category | File | Line | Issue |`,
      `|---|---|---|---|---|`
    );

    for (const f of findings) {
      const sEmoji = SEVERITY_EMOJI[f.severity] || "";
      const cEmoji = CATEGORY_EMOJI[f.category] || "";
      lines.push(
        `| ${sEmoji} ${f.severity} | ${cEmoji} ${f.category} | \`${f.file}\` | ${f.line} | **${f.title}** |`
      );
    }

    lines.push(`</details>`);
  } else {
    lines.push(``, `✅ **No active issues found. Clean code!**`);
  }

  lines.push(
    ``,
    `---`,
    `*Generated by **PR Guardian** using Google Gemini (\`${model}\`). Updated: ${new Date().toUTCString()}*`
  );

  return lines.join("\n");
}

module.exports = {
  formatInlineComment,
  formatSummary,
  SEVERITY_EMOJI,
  CATEGORY_EMOJI,
  SEVERITY_ORDER,
  CATEGORY_ORDER,
};
